### ISSUE TITLE
Can't move .iso files, filesystem error

### ISSUE THREAD

**Issue by lanzorg** [paolo-projects/auto-unlocker#20]
I installed the latest (v1.1) .DEB release from here:  
https://github.com/paolo-projects/auto-unlocker/releases/download/v1.1/autounlocker_1.1.0_amd64.deb

I executed the auto-unlocker from ~/.auto-unlocker directory:

```sh
auto_unlocker_dir="${HOME}/.auto-unlocker"
mkdir -p "${auto_unlocker_dir}" && cd "${auto_unlocker_dir}"
sudo auto-unlocker --install
```

Everything works except it can't copy the .iso files:

```sh
Copying tools into program directory...
Error: filesystem error: cannot copy file: No such file or directory [./tools/darwin.iso] [/usr/lib/vmware/isoimages/darwin.iso]
Error: filesystem error: cannot copy file: No such file or directory [./tools/darwinPre15.iso] [/usr/lib/vmware/isoimages/darwinPre15.iso]
Patch complete.
```

The problem is that those .iso files are stored into ~/.auto-unlocker not ~/.auto-unlocker/tools.

![](https://i.imgur.com/Oci3eXJ.png)

PS: Could you remove the press enter to quit at the end? ;)

**Comment by paolo-projects** [comment]
Thank you for the report. It seems the tools folder gets merged into the file name without a **/** to separate them. There's probably something I need to fix in the code. You can easily get around it by moving them manually like this
```
sudo mv ./toolsdarwin.iso /usr/lib/vmware/isoimages/darwin.iso && sudo mv ./toolsdarwinPre15.iso /usr/lib/vmware/isoimages/darwinPre15.iso
```
On top of that I think that the tools are being included into the most recent vmware installers so I'd double check that they are not already there.

> PS: Could you remove the press enter to quit at the end? ;)

I guess I'll just make it a windows only feature since on linux it's usually being run in a separate shell and you are able to see the output.

**Comment by lanzorg** [comment]
Glad I could help. ;)

**Comment by lanzorg** [comment]
Are you going to make a new release and new .deb package?

**Comment by paolo-projects** [comment]
> 
> 
> Are you going to make a new release and new .deb package?

I don't have a toolchain set up atm but I hope I'll be able to get it working soon.

I was also thinking of building an AppImage instead of the deb to avoid installing a package for a one time task
