### ISSUE TITLE
How do you compile this thing under Windows 10 / 64 bit?

### ISSUE THREAD

**Issue by jayk1961** [paolo-projects/auto-unlocker#4]
I'm using cygwin64. There's some C++ issues, obviously. I was able to fix some with adding 
-lstdc++fs.

I tried setting the following:
-std=c++17
-std=gnu++17

and
-std=c++98 
-std=gnu++98

Either way, once I was able to get a binary built, it crashed with:
Error: OS not supported

Did you use gcc, gcc 64bit, or mingw-w64?

The file I built says:
$ file Unlocker.exe
Unlocker.exe: PE32+ executable (console) x86-64, for MS Windows

Your file matches mine:
$ file Unlocker.exe
Unlocker.exe: PE32+ executable (console) x86-64, for MS Windows

**Comment by paolo-projects** [comment]
you can find all the info about compiling the software in the [README](https://github.com/paolo-projects/auto-unlocker/blob/master/README.md). 

The g++ compatibility is specified here:

> Note regarding default g++ version on Ubuntu: by default, Ubuntu ships with g++ v7, which doesn't support natively c++17 features. To compile the program you have to install at least g++-8, set CXX variable when running make and add stdc++fs library dependence (make CXX=g++-8 LIBS=-lstdc++fs)
>
> Alternatively, you can install g++-9 and avoid adding the library dependency.

I compiled it on windows with VC 2019 (there's a cmake file included that fully supports MSVC, you have to point it to your compiled libraries), although you should be able to compile it with mingw and cygwin too, after you install/compile the dependencies. As for your error, it's because cygwin is not a `_WIN32` nor a `__linux__` platform, and since you probably are using g++ then I guess it's just fine if you 
`#define __linux__` 
at the beginning of *unlocker.cpp*

**Comment by jayk1961** [comment]
My toolchain is set up to use mingw-64. The latest it version 7.4.0 it says:

/usr/lib/gcc/x86_64-w64-mingw32/7.4.0/lto-wrapper.exe

gcc states:
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/8.3.0/lto-wrapper.exe
Target: x86_64-pc-cygwin


However, I'd much rather use VC 2019. So, I will go that route.

**Comment by paolo-projects** [comment]
g++8 works, it only requires an additional linker dependency for filesystem library (*-lstdc++fs*). That's because fs was still experimental, although I tested it on ubuntu with both g++8 and g++9 and it works fine.
cygwin is another story. what I said earlier, i.e. to put a `#define __linux__` in unlocker.cpp, is **wrong** and you should not do it because it will attempt to patch the linux files structure. you could try to go with `#define _WIN32` but ultimately I suggest you to use mingw or even better visual studio.
