### ISSUE TITLE
question

### ISSUE THREAD

**Issue by linuxerlv** [paolo-projects/auto-unlocker#8]
In some cases, the download speed of this software is very slow. Can you add the option of installing files locally?
Thanks.

**Comment by paolo-projects** [comment]
it was already in a planned commit, now I pushed the updates to the repo.
you let the app download the tools once, then you copy the newly created tools folder along with the exe to avoid redownloading them on another installation. it will ask you what to do, just type y to use the existing tools.
I've also added a new windows release with the modifications

**Comment by DRSDavidSoft** [comment]
I think it would be better to just display the URL, let the user download the file, then let the C++ code take care of decompressing tar/zip file.

A good reason for this is that the `libcurl` handle in the code is non-configurable, and a user might need to use a corporate proxy in order to download the tools.

**Comment by paolo-projects** [comment]
Well I think it's a pretty uncommon use case. An experienced user could as well manually download the tools, extract them into the tools folder, and then the tool will just pick them instead of downloading them again.

**Comment by DRSDavidSoft** [comment]
@paolo-projects That would be even better (if the user has already downloaded the tools, it's best to just extract them into the directory manually -- instead of the code doing it).

I would appreciate it if you could add some documentation on the procedure and what should the directory contain on different platforms, as well as putting the [`config.h`](https://github.com/paolo-projects/auto-unlocker/blob/master/include/config.h) values into the documentation as well.
